name: emartconsumer
description: Application for eMart user.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^15.1.1
  flutter_facebook_auth: ^5.0.11
  geoflutterfire2: ^2.3.15
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  #payment getway
  mercadopago_sdk: ^1.3.0
  flutter_stripe: ^9.2.0
  paytm_allinonesdk: ^1.2.1
  flutterwave_standard: ^1.0.7
  #razorpay_flutter: ^1.3.5
  flutter_braintree: ^3.0.0

  google_fonts: ^4.0.4
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_datepicker: ^21.2.3
  image_picker: ^0.8.7+5
  url_launcher: ^6.1.11
  progress_dialog_null_safe: ^1.0.7
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  uuid: ^3.0.7
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.15
  photo_view: ^0.14.0
  video_player: ^2.6.1
  http: ^0.13.6
  smooth_page_indicator: ^1.1.0
  intl_phone_number_input: ^0.7.3+1
  pin_code_fields: ^7.4.0
  permission_handler: ^10.2.0
  easy_localization: ^3.0.1
  mime: ^1.0.4
  moor_flutter:
  path: ^1.8.2
  font_awesome_flutter: ^10.4.0
  flutter_polyline_points: ^1.0.0
  percent_indicator: ^4.2.3
  lottie: ^2.3.2
  flutter_native_image: ^0.0.6+1
  video_compress: ^3.1.2
  flutter_sound: ^9.2.13
  the_apple_sign_in:
  cupertino_icons: ^1.0.5
  dotted_border: ^2.0.0+3
  flutter_rating_bar: ^4.0.1
  place_picker: ^0.10.0
  google_maps_flutter: ^2.2.8
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2
  clipboard: ^0.1.3
  location: ^5.0.3
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: ^1.1.0
  flutter_facebook_keyhash: ^0.0.4
  flutter_qr_bar_scanner: ^3.0.2
  flutter_widget_from_html: ^0.10.1
  scroll_to_index: ^3.0.1
  rect_getter: ^1.1.0
  story_view: ^0.14.0
  flutter_share: ^2.0.0
  flutterflow_paginate_firestore: ^1.0.3+1
  google_maps_place_picker_mb: ^3.0.2

dependency_overrides:
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo_new.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo_new.png
  image_dark: assets/images/app_logo_new.png

  android_12:
    image: assets/images/app_logo_new.png
    image_dark: assets/images/app_logo_new.png

  web: false


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/
    - assets/
